name: Build and Push Versioned Docker Image to GHCR

on:
  push:
    branches:
      - main  # ✅ Trigger only when changes are pushed (merged) into 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAJAN }}  # Use your PAT for pushing version bump

      - name: Set up Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Read and bump version
        id: bump_version
        run: |
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"

          # Extract version parts
          PATCH=$(echo "$VERSION" | awk -F ':' '{print $4}')
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="V:1:0:$NEW_PATCH"
          echo "$NEW_VERSION" > version.txt

          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=tag::${NEW_VERSION//:/-}"  # e.g. V-1-0-1

      - name: Commit updated version.txt
        run: |
          git add version.txt
          git commit -m "Bump version to $NEW_VERSION"
          git push origin main

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cloudsajan
          password: ${{ secrets.SAJAN }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=ghcr.io/cloudsajan/dbtez-test:${{ steps.bump_version.outputs.tag }}
          docker build -t $IMAGE_TAG .

      - name: Push Docker image to GHCR
        run: |
          IMAGE_TAG=ghcr.io/cloudsajan/dbtez-test:${{ steps.bump_version.outputs.tag }}
          docker push $IMAGE_TAG
