name: Build and Push Versioned Docker Image to GHCR

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SAJAN }}  # Required for pushing version bump

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Read and bump version
        id: bump_version
        run: |
          VERSION=$(cat version.txt)
          echo "Current version: $VERSION"
          # Parse and increment patch version
          BASE=$(echo "$VERSION" | cut -d':' -f1,2,3)
          PATCH=$(echo "$VERSION" | cut -d':' -f4)
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="V:1:0:$NEW_PATCH"
          echo "$NEW_VERSION" > version.txt
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "::set-output name=tag::${NEW_VERSION//:/-}"

      - name: Commit new version.txt
        run: |
          git add version.txt
          git commit -m "Bump version to $NEW_VERSION"
          git push origin develop

      - name: Log in to GHCR with PAT
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: cloudsajan
          password: ${{ secrets.SAJAN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_TAG=ghcr.io/cloudsajan/dbtez-test:${{ steps.bump_version.outputs.tag }}
          docker build -t $IMAGE_TAG .

      - name: Push Docker image
        run: |
          IMAGE_TAG=ghcr.io/cloudsajan/dbtez-test:${{ steps.bump_version.outputs.tag }}
          docker push $IMAGE_TAG
